import auth from './auth';
import profile from './profile';
import boosterPanel from './booster-panel';
import waitme from './waitme';
import clientPanel from './client';
import payment from './payment';
import app from './app';
import paypal from './paypal';
import topup from './topup';
var actions = _.merge({},auth, profile, waitme, boosterPanel, payment, clientPanel, app, paypal, topup);
cc.register('redux.actions', actions);
