import auth from './auth';
import profile from './profile';
import boosterPanel from './booster-panel';
import waitme from './waitme';
import clientPanel from './client';
import payment from './payment';
import app from './app';
import paypal from './paypal';
var actions = _.merge({},auth, profile, waitme, boosterPanel, payment, clientPanel, app, paypal);
cc.register('redux.actions', actions);
