var constant = {
  SIGNIN_CB: 'SIGNIN_CB',
  SIGNUP_CB: 'SIGNUP_CB',
  SIGNOUT: 'SIGNOUT',
  PROFILE_CB: 'PROFILE_CB',
  CONTACTLIST_CB: 'CONTACTLIST_CB',
  HISTORY_CB: 'HISTORY_CB',
  FILTER_CUSTOMER_NAME: 'FILTER_CUSTOMER_NAME',
  CURRENT_TICKET_CB: 'CURRENT_TICKET_CB',
  SHOW_LOADER: 'SHOW_LOADER',
  TOGGLE_CONFIRM_DIALOG: 'TOGGLE_CONFIRM_DIALOG',
  START_BOOSTING_CB: 'START_BOOSTING_CB',
  CREATE_TICKET_CB: 'CREATE_TICKET_CB'
};
cc.register('redux.constants', constant);
