var constant = {
  SIGNIN_CB: 'SIGNIN_CB',
  SIGNUP_CB: 'SIGNUP_CB',
  SIGNOUT: 'SIGNOUT',
  PROFILE_CB: 'PROFILE_CB',
  CONTACTLIST_CB: 'CONTACTLIST_CB',
  HISTORY_CB: 'HISTORY_CB',
  FILTER_CUSTOMER_NAME: 'FILTER_CUSTOMER_NAME',
  CURRENT_TICKET_CB: 'CURRENT_TICKET_CB',
  SHOW_LOADER: 'SHOW_LOADER',
  TOGGLE_CONFIRM_DIALOG: 'TOGGLE_CONFIRM_DIALOG',
  START_BOOSTING_CB: 'START_BOOSTING_CB',
  BUY_TICKET_CB: 'BUY_TICKET_CB',
  TOGGLE_BUY_TICKET_CONFIRM_DIALOG: 'TOGGLE_BUY_TICKET_CONFIRM_DIALOG',
  GET_TICKET_CB: 'GET_TICKET_CB',
  DONE_BOOSTING_CB: 'DONE_BOOSTING_CB',
  SHOW_ALERT_DIALOG: 'SHOW_ALERT_DIALOG',
  GET_PICKED_TICKET_CB: 'GET_PICKED_TICKET_CB',
  PAY_PICKED_TICKET_CB: 'PAY_PICKED_TICKET_CB',
  CANCEL_PICKED_TICKET_CB: 'CANCEL_PICKED_TICKET_CB'
};
cc.register('redux.constants', constant);
