var constant = {
  SIGNIN_CB: 'SIGNIN_CB',
  SIGNUP_CB: 'SIGNUP_CB',
  SIGNOUT: 'SIGNOUT',
  PROFILE_CB: 'PROFILE_CB',
  CONTACTLIST_CB: 'CONTACTLIST_CB',
  HISTORY_CB: 'HISTORY_CB',
  FILTER_CUSTOMER_NAME: 'FILTER_CUSTOMER_NAME',
  CURRENT_TICKET_CB: 'CURRENT_TICKET_CB'
};
cc.register('redux.constants', constant);
