# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Contact date')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_mmr', models.PositiveIntegerField(verbose_name='minimum MMR')),
                ('max_mmr', models.PositiveIntegerField(verbose_name='maximum MMR')),
                ('day_used', models.PositiveIntegerField(verbose_name='day used to boost MMR')),
                ('status', models.IntegerField(choices=[(1, 'available'), (2, 'boosting'), (3, 'waiting for payment'), (4, 'done')])),
                ('current_mmr', models.PositiveIntegerField(blank=True, null=True, verbose_name='current MMR')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
        ),
    ]
