# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_mmr', models.PositiveIntegerField(verbose_name='minimum MMR')),
                ('max_mmr', models.PositiveIntegerField(verbose_name='maximum MMR')),
                ('day_used', models.PositiveIntegerField(verbose_name='day used to boost MMR')),
                ('status', models.CharField(choices=[('A', 'available'), ('B', 'boosting'), ('WP', 'waiting for payment'), ('D', 'done')], max_length=2)),
                ('current_mmr', models.PositiveIntegerField(null=True, verbose_name='current MMR')),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
