# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='clients',
            field=models.ManyToManyField(blank=True, through='ticket_system.Clientship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientship',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientship',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_system.Ticket'),
        ),
    ]
