# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (2, 'boosting'), (3, 'waiting for payment'), (4, 'done')]),
        ),
    ]
