# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0002_auto_20161028_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='current_mmr',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='current MMR'),
        ),
    ]
