# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0002_auto_20161030_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientList',
            new_name='Clientship',
        ),
    ]
