# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0003_auto_20161029_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='price'),
            preserve_default=False,
        ),
    ]
