# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_system', '0004_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='client',
        ),
        migrations.AddField(
            model_name='clientlist',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_system.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='clients',
            field=models.ManyToManyField(through='ticket_system.ClientList', to=settings.AUTH_USER_MODEL),
        ),
    ]
