# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_booster',
            field=models.BooleanField(default=False, verbose_name='booster'),
        ),
    ]
