# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_boosted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin',
            field=models.PositiveIntegerField(default=0, verbose_name='coin'),
        ),
    ]
